// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewLink struct {
	Link   string `json:"link"`
	Code   int    `json:"code"`
	UserID string `json:"user_id"`
}

type NewUser struct {
	Name     string `json:"name"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type UpdateUser struct {
	Name           string `json:"Name"`
	Email          string `json:"Email"`
	PhotoProfile   string `json:"PhotoProfile"`
	Headline       string `json:"Headline"`
	BgPhotoProfile string `json:"BgPhotoProfile"`
}

type ValidChangePass struct {
	ID   string `json:"id"`
	Code int    `json:"code"`
}

type ValidReq struct {
	ID   string `json:"id"`
	Code int    `json:"code"`
}
